version: 0.0
os: linux
files:
  - source: scripts/newcode
    destination: /var/www/html/
permissions:
  - object: /var/www/html/
    pattern: "**"
    owner: ec2-user
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
      mode: 777
  AfterInstall:
    - location: scripts/change_permissions.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user

