#testing webhook
version: 0.0
os: linux
files:
  - source: script/newcode
    destination: /var/www/html
permissions:
  - object: /var/www/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: ./script/install_dependencies.sh
      timeout: 301
      runas: ec2-user
  AfterInstall:
    - location: ./script/install_dependencies01.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: ./script/start_server.sh
      timeout: 300
      runas: ec2-user


