#testing webhook
version: 0.0
os: linux
files:
  - source: scripts/newcode
    destination: /var/www/html
permissions:
  - object: /var/www/html
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 301
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies01.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root


